# Generated by Django 2.1.3 on 2019-09-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('textoTitulo', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('TextoAnuncio', models.CharField(max_length=50)),
                ('nomeContato', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('secao', models.CharField(max_length=50)),
                ('tipoAnuncio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricaoProduto', models.CharField(max_length=50)),
                ('unidadeCompra', models.CharField(max_length=50)),
                ('qtdPrevistoMes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('precoMaximo', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
